-- Migration 001: Recommendation enum unification + curated productIds
--
-- Why:
--   1. status CHECK constraint drifted across DB (pending|dm_sent|completed|failed),
--      backend routes (pending|processing|completed), and frontend types
--      (pending|processing|completed). Canonical set is now
--      pending|processing|completed|failed. `dm_sent` was a side-channel
--      timestamp, not a workflow state; the `dm_sent_at` column is kept.
--   2. Admins now curate recommended products by hand. Add `product_ids TEXT[]`
--      to persist the curated set per recommendation.
--
-- Idempotency: safe to re-run.
-- This script does NOT run automatically. Apply via:
--   psql "$DATABASE_URL" -f src/db/migrations/001_recommendation_enum_and_product_ids.sql

BEGIN;

-- 1. Add product_ids column (PG TEXT[] for parity with products.personal_colors)
ALTER TABLE recommendations
    ADD COLUMN IF NOT EXISTS product_ids TEXT[] NOT NULL DEFAULT '{}';

-- 2. Migrate any legacy `dm_sent` rows to `completed` so the new CHECK passes.
--    `dm_sent_at` column already records the side-channel timestamp.
UPDATE recommendations
SET status = 'completed'
WHERE status = 'dm_sent';

-- 3. Replace the status CHECK constraint with the canonical enum.
--    The constraint name is generated by Postgres; drop any existing
--    CHECK on `status` defensively before re-adding.
DO $$
DECLARE
    conname TEXT;
BEGIN
    FOR conname IN
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        WHERE rel.relname = 'recommendations'
          AND con.contype = 'c'
          AND pg_get_constraintdef(con.oid) ILIKE '%status%'
    LOOP
        EXECUTE format('ALTER TABLE recommendations DROP CONSTRAINT %I', conname);
    END LOOP;
END
$$;

ALTER TABLE recommendations
    ADD CONSTRAINT recommendations_status_check
    CHECK (status IN ('pending', 'processing', 'completed', 'failed'));

COMMIT;
